name: Deploy to Vercel

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build frontend with Maven
        run: mvn install

      - name: Start Java Spring app
        run: mvn spring-boot:run

      - name: Deploy frontend to Vercel
        uses: amondnet/vercel-action@v20
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          prod: true
          dir: frontend/target
